update the pages 'available questionnaires for a group' and 'impersonate'
w3c/wbs-design pull request #25
Opened 2016-09-12 14:17 UTC by lcarcone

I have added the Material icon 'Add'

Thanks

2016-09-16 16:16 UTC, tripu commented on css/site-wbs-style.css
> + // margin-left:-1em;
Is `//` valid for CSS comments? I thought only `/* */` was legal&hellip;

2016-09-16 16:17 UTC, tripu commented on css/site-wbs-style.css
> + // content:"\0bb";
Is `//` valid for CSS comments? I thought only `/* */` was legal&hellip;

2016-09-16 16:21 UTC, tripu commented on html/qtypes-site-current.html
> +  class='icon' href='test-call/results' title='Results of &quot;Call for Review: HTML tidy service is W3C Proposed Recommendation&quot;'><img src='../icons/list.png' alt='List' /></a> </span><br /></
I like our new icons, but sometimes they're not intuitive enough.

`icons/stock_edit.png` clearly means &ldquo;edit&rdquo;. But `icons/list.png` doesn't scream &ldquo;results&rdquo;.

I don't think we'd find an icon for &ldquo;results&rdquo; that is clear for all users. So, maybe add a label next to it&hellip;?

2016-09-16 16:21 UTC, tripu requested changes
LGTM if we address these comments.

2016-09-19 13:24 UTC, lcarcone commented on html/qtypes-site-current.html
> +  class='icon' href='test-call/results' title='Results of &quot;Call for Review: HTML tidy service is W3C Proposed Recommendation&quot;'><img src='../icons/list.png' alt='List' /></a> </span><br /></
@tripu I fixed the css and added a title for icons Edit/Results.
Is it ok for you ?

2016-09-19 14:02 UTC, tripu approved these changes

2016-09-19 14:03 UTC, merged

2016-09-19 14:03 UTC, tripu commented
Thank you, @lcarcone!