Account choice
w3c/wbs-design pull request #29
Opened 2016-10-12 19:23 UTC by lcarcone

Hi Tripu,

I have added the page 'Use an account or not' and I have modified it's style.

Thanks,
Laurent

2016-10-14 14:14 UTC, tripu requested changes
:+1: except for those two tiny suggestions.

2016-10-14 14:14 UTC, tripu commented on css/site-wbs-style.css
> +ul.account li.main:hover {
I'd remove the hover effect; I think it's more confusing than anything.
(It's useful on long tables and things like that to help the user know what row they're pointing at; but this is a small selection among two options only.)

2016-10-14 14:14 UTC, tripu commented on html/account-choice.html
> +<a href='https://www.w3.org/2002/09/wbs/99999/wbs-types-test/?login'>YES</a> &#xA0; </strong>
I'd remove the hyperlink in &ldquo;YES&rdquo;; it's redundant and a bit confusing. Also, there is no hyperlink in &ldquo;NO&rdquo;.

2016-10-17 09:35 UTC, tripu commented
@lcarcone, what do you think about my comments above?

2016-10-17 09:44 UTC, lcarcone commented
Hi Tripu, ok with both suggestions

2016-10-18 20:01 UTC, lcarcone commented
Hi tripu,
I took your suggestions into account.
Thanks

2016-10-19 06:34 UTC, tripu approved these changes

2016-10-19 06:35 UTC, merged