make some tables scrollable
w3c/wbs-design pull request #34
Opened 2017-01-09 11:53 UTC by lcarcone

Hi Tripu,

I made small changes to make some large tables scrollable (questions 13 and 15).
It is not complete as I'd like the first column to be fixed so that it would be easy to scroll the table horizontally, but I haven't yet found a solution to do that without js.
Maybe you know a css solution, otherwise we can ask Bert.
What do you think ?

Thanks,
Laurent

2017-01-24 14:41 UTC, lcarcone commented
Hi Tripu,

I adapted a css tip from Bert to have a scrollable table with fixed first colum.
It's specific to questions 13 and 15 for the moment, there are still some work to do if we want to generalize it to all tables.
I had to override a rule of the w3c site css to have this solution to work, I have to check it doesn't break something else.

I have also tested 2 jquery plugins: dataTables and fixedColumns. 
I had some problems to use fixedColumns with our examples.
DataTables can help us to do vertical scrolling with fixed header (I don't know if there is a css tip to do that). It is quite powerful to manage tables, maybe we can look at it to improve the usability of results page.

Thanks,
Laurent

2017-01-24 17:06 UTC, tripu requested changes
@lcarcone, :+1:!

A couple of suggestions.

Perhaps you don't need to wrap tables on a new `div`; instead, add the necessary class (`scroll`) to the existing `table`.

Complex table headings (when there is more than one `tr` inside `thead`) don't seem to behave well when scrolling. I tried to tweak properties of several elements in CSS to anchor that first column better, but I don't like results either. I wonder if it won't be better to leave all columns with their default `position: static`, even if the first column isn't visible when the user scrolls&hellip;

2017-01-25 14:11 UTC, tripu commented
(This fixes #28.)

2017-01-31 07:26 UTC, lcarcone commented
@tripu
I made several tests, the class (scroll) must be on the parent wrapper, it doesn't work on the table itself.
I also made several tests to have the first header column fixed but without success. I removed the property 'position: absolute;' on the  first date cell for the moment, I'll do more tests when it is merged.
Thanks

2017-01-31 09:37 UTC, tripu requested changes
:+1:, barring my comment about comments :)

2017-01-31 09:37 UTC, tripu commented on css/site-wbs-style.css
> +   // position: absolute;
Use `/* */` instead (but I'd say you can remove the property altogether).

[`w3.org/TR/CSS2`](https://www.w3.org/TR/CSS2/syndata.html#comments)
[`w3.org/TR/css-syntax-3`](https://www.w3.org/TR/css-syntax-3/#comment-diagram)

2017-01-31 10:09 UTC, lcarcone commented
I removed the property, thanks

2017-01-31 12:22 UTC, tripu approved these changes

2017-01-31 12:22 UTC, merged