Use the Nav element
w3c/wbs-design pull request #70
Opened 2018-08-28 09:38 UTC by lcarcone

I have modified the file index-site-select2.html to use the <nav> element as suggested by Leonie Watson in issue https://github.com/w3c/wbs-design/issues/48
If it is ok I'll report the modif in WBS code

Laurent

2018-08-31 14:37 UTC, tripu commented
(Description edited slightly to fix formatting)

2018-08-31 21:46 UTC, LJWatson commented
LGTM. Thank you.

2018-09-10 15:23 UTC, tripu requested changes
I suggest we also take the opportunity to upgrade the *doctype* here, to `<!DOCTYPE html>`.

2018-09-10 15:23 UTC, tripu commented on html/index-site-select2.html
> +   <nav id="w3c_nav" aria-label="Main">
The top-level menu *&ldquo;Views: desktop mobile print&rdquo;* seems to be created via JS. There's something in this new layout that prevents that menu from showing. I guess the JS code needs to be updated at the same time, too.

2018-09-11 13:13 UTC, tripu commented on html/index-site-select2.html
> +   <nav id="w3c_nav" aria-label="Main">
I think it's (at least), line no. 2023 of [`https://www.w3.org/2008/site/js/main`](https://www.w3.org/2008/site/js/main):

```js
G("#w3c_nav div.w3c_sec_nav").append(⋯)
```

It doesn't work because what used to be

```html
<div class="w3c_sec_nav">
```

is now

```html
<nav class="w3c_sec_nav" aria-label="Secondary">
```

There might be other selectors that need to be adapted, too.

2018-09-11 13:23 UTC, lcarcone commented on html/index-site-select2.html
> +   <nav id="w3c_nav" aria-label="Main">
Yes, I thought it was because I replaced the element div by the element nav.
I'll work on this problem, thanks for pointing me to the right js part.

2018-09-18 20:03 UTC, lcarcone commented
I restored the div elements used to build the menu 'views' at the top. I still use the nav elements in this example, so I guess it's still ok regarding accessibility.
About the menu 'views', it is not working on the index page (while it seems to work for the page my_questionnaires.html), maybe it's because we use the library jquery with the w3c main js).
Btw, this menu is not working very well on some pages of the W3C site, so it not seems to be specific to WBS. I'd propose to separate the problems.
Is the use of the nav elements ok for you now ?

2018-09-27 07:08 UTC, tripu reviewed
Why the change in size of the two PNG images?

2018-09-27 07:08 UTC, tripu commented on html/index-site-select2.html
> +       <button id="search-submit" name="search-submit" type="submit"><img class="submit" src="http://www.w3.org/2008/site/images/search-button" alt="Search" width="21" height="17" /></button>
Better use `https://`?

2018-09-28 09:35 UTC, lcarcone commented on html/index-site-select2.html
> +       <button id="search-submit" name="search-submit" type="submit"><img class="submit" src="http://www.w3.org/2008/site/images/search-button" alt="Search" width="21" height="17" /></button>
Changed. 
That part won't be modified in WBS code, it will still use 'src="//www.w3.org/...' so, implicitely https:// 
It was just to load the icon in this github document

2018-09-28 09:43 UTC, lcarcone commented
I changed the size of the equivalent icons in WBS because they were bigger than the other ones in the 'mobile' view. I reported those changes in the github repository.
The names of the icons differ between WBS and github repo (I had to change the names when I started to implement the new design in production to not break the old style).
When we have time it would be nice to harmonize them now that the code related to the old style has been removed from WBS. But it is not related to that specific issue, we can create a new one as a reminder.

2018-10-01 09:52 UTC, lcarcone commented
I changed http into https. 
Btw, no protocol is used in WBS code, (it uses 'src="//www.w3.org/...' so, implicitely https://)

2018-10-01 15:27 UTC, tripu approved these changes

2018-10-01 15:27 UTC, merged